### ISSUE TITLE
Code is not licensed

### ISSUE THREAD

**Issue by rebeccapeltz** [osandadeshan/markdown-quiz-generator#5]
I want to reuse some of the code in this repository.  Could you add a license? For example, an MIT license https://opensource.org/license/mit.

**Comment by osandadeshan** [comment]
Hi @rebeccapeltz 
Thanks for highlighting this. I have added MIT license to the repository.
https://github.com/osandadeshan/markdown-quiz-generator/blob/master/LICENSE

**Comment by osandadeshan** [comment]
Hi @rebeccapeltz
Thanks for highlighting this. I have added MIT license to the repository.
https://github.com/osandadeshan/markdown-quiz-generator/blob/master/LICENSE

**Comment by rebeccapeltz** [comment]
Thank you!
